// <auto-generated />
using System;
using KeywordScan.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeywordScan.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250424083402_MigrationName3")]
    partial class MigrationName3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KeywordScan.Web.Models.WebSearchResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Messages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionsIndex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RowCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RunTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SearchEngine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebSearchResponse");
                });
#pragma warning restore 612, 618
        }
    }
}
